### PR TITLE
Make defmodel take protocol implementations

### LINKED ISSUE #1: Support (empty) on models
Something like 

```clojure
(empty User)
```

currently doesn't work.

### LINKED ISSUE #2: Support invoking models via apply
e.g.

```clojure
(apply User [:first-name "Cam", :last-name "Saul"])
```

Looks like we need to implement [`clojure.lang.IFn/applyTo`](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/IFn.java#L95)

### LINKED ISSUE #9: Allow extending protocols right from defmodel
The current way of specifying hydration keys is rather unwieldy, so I came up with this

``` clojure
(defmodel Video :videos
  models/IModel
  (hydration-keys [_]
    [:video :preview_video]))
```

I have a working patch (see [this gist](https://gist.github.com/3b58aba0861bd5358fc71c6f4cce5fa3)). Happy to submit it, just wanted to check first if this is something you'd be interested in.

### PR DESCRIPTION
**Pull request by plexus**
Pass implementations of protocols directly to `defmodel`, the same way you would
do in `defrecord` or `deftype`. (fixes #9)

Also provides implementations for `empty` (fixes #1) and `apply` (fixes #2).

This updates the documentation, promoting this way of doing things as the
preferred method (vs using extend...merge...IModelDefaults), but still leaves in
an example of how to do things the old-fashioned way.

The defining-models doc has been expanded slightly to further clarify the
relationship between `User` and `(User 1`).

The fill column in that document was irregular but seemed to hover around 120,
so I went with breaking lines at 120 characters. It might be best to ignore
whitespace changes when reviewing this.

Note that as it stands you can implement protocols in `defmodel`, but not
interfaces, since the forms are inserted in `extend` rather than in `defrecord`
itself. To fix this we'll have to separate extensions to IModel from other
interface/protocol implementations.

### CODE REVIEW

**Comment by plexus** [comment]
Diff ignoring whitespace: https://github.com/metabase/toucan/pull/14/files?w=1

**Comment by plexus** [comment]
I'll update VERSION-HISTORY once #13 is merged, or we'll be getting conflicts.

File: test/toucan/models_test.clj [hunk 1]
```diff
@@ -159,6 +159,11 @@
  #toucan.test_models.venue.VenueInstance{:category :store, :name "BevMo", :id 3}
  (Venue :name "BevMo"))
 
+;; Test invoking model as a function with apply
+(expect
+ #toucan.test_models.venue.VenueInstance{:category :store, :name "BevMo", :id 3}
+ (apply Venue [:name "BevMo"]))
```
Comment (camsaul) [inline test/toucan/models_test.clj]: 👍

**Comment by camsaul** [comment]
@plexus sorry for the delay. I'll take a look at this and your other PR

File: docs/defining-models.md [hunk 2]
```diff
@@ -1,11 +1,10 @@
...
-In Toucan, you define the various *models* used in your application with `defmodel`.
-Models encapsulate information and behaviors related to a specific table in the application DB,
-and have their own unique record type.
+In Toucan, you define the various *models* used in your application with `defmodel`. Models encapsulate information and
+behaviors related to a specific table in the application DB, and have their own unique record type.
 
-Generally, a single Toucan model corresponds to a single table in your database. Common models might
-be things like `User` or `Venue`.
+Generally, a single Toucan model corresponds to a single table in your database. Common models might be things like
+`User` or `Venue`.
```
Comment (camsaul) [inline docs/defining-models.md]: what's the reason behind changing these lines? 

it makes it a lot harder to review PRs when things are randomly changed like this for no reason

File: docs/defining-models.md [hunk 3]
```diff
@@ -20,49 +19,81 @@ The `defmodel` macro is used to define a new model:
...
+(User 1) ;;=> #my.ns.UserInstance{:id 1, :first_name "Rapid", :last_name "Raccoon"}
+```
+
+This way they can share the `IModel` protocol (discussed below) and simplifies the interface; functions like `types`
+work on either the model itself (e.g., `User`) or instances fetched from the DB.
 
 In other words, both of the following work:
 
-```clojure
+``` clojure
```
Comment (camsaul) [inline docs/defining-models.md]: why

File: docs/defining-models.md [hunk 4]
```diff
@@ -20,49 +19,81 @@ The `defmodel` macro is used to define a new model:
...
 
-Note that `User` itself is not a class, but rather a definition of the `User` model, and is itself an instance of `UserInstance`;
-hence the call to `extend` `(class User)`.
+Note that `User` itself is not a class, but rather a definition of the `User` model, and is itself an instance of
+`UserInstance`; hence the call to `extend` `(class User)`.
 
-Refer to the documentation below for an overview of the various methods provided by `IModel` and how to use them to customize
-the behavior of your models.
+Refer to the documentation below for an overview of the various methods provided by `IModel` and how to use them to
+customize the behavior of your models.
```
Comment (camsaul) [inline docs/defining-models.md]: again, random edits like this that don't affect the way the markdown renders make this PR a lot bigger (and thus a lot harder to review), so what's the reason behind them?

File: docs/defining-models.md [hunk 5]
```diff
@@ -292,13 +320,14 @@ any desired changes.
...
 
 ```clojure
-(defn- pre-insert [user]
-  (let [defaults {:version 1}]
-    (merge defaults user))) ; set some default values"
-
-(extend (class User)
-  IModel (merge IModelDefaults
-                {:pre-insert pre-insert}))
+(defn- )
```
Comment (camsaul) [inline docs/defining-models.md]: did you mean to remove this?

File: docs/defining-models.md [hunk 6]
```diff
@@ -292,13 +320,14 @@ any desired changes.
...
+
+(defmodel User :user_table
+  IModel
+  (pre-insert [user]
+    (let [defaults {:version 1}]
+      (merge defaults user) ; set some default values"
+      )))
```
Comment (camsaul) [inline docs/defining-models.md]: hanging parens = bad

this should look like `)))) ; set some default values`

File: src/toucan/models.clj [hunk 7]
```diff
@@ -371,6 +373,45 @@
 ;;;                                                      DEFMODEL MACRO
 ;;; ========================================================================================================================
 
+(defn- ifn-invoke-forms
+  "Macro helper, generates
```
Comment (camsaul) [inline src/toucan/models.clj]: generates what?

File: src/toucan/models.clj [hunk 8]
```diff
@@ -371,6 +373,45 @@
...
+
+       (~'invoke [this#]
+        (invoke-model-or-instance this#))
+       (~'invoke [this# id#]
+        (invoke-model-or-instance this# id#))
+       (~'invoke [this# arg1# arg2#]
+        (invoke-model-or-instance this# arg1# arg2#))
+       ,,,"
```
Comment (camsaul) [inline src/toucan/models.clj]: I think you meant to put `...`

**Comment by camsaul** [comment]
@plexus don't worry about updating the VERSION-HISTORY, I'll do it when I push out a new release

File: src/toucan/models.clj (hunk 8 above)
Comment (plexus) [inline src/toucan/models.clj]: `,,,` is called a "fogus comma", it's some used in Clojure docs (e.g. [this one](https://clojure.org/guides/threading_macros), as well by [PragProg](https://media.pragprog.com/titles/vmclojeco/intro.pdf)

2017-06-01-145244_615x93_scrot

I can change it though if you don't like it.

**Comment by plexus** [comment]
I cleaned things up that were pointed out in the review. My apologies for making seemingly arbitrary changes, I reverted them. I tend to use emacs' fill-paragraph functionality a lot when writing docs. However in this case it seems the docs are wrapped by hand, so their fill-column isn't consistent.

File: src/toucan/models.clj (hunk 8 above)
Comment (camsaul) [inline src/toucan/models.clj]: Got it. I haven't seen that before, but it works for me 👍

**Comment by camsaul** [comment]
@plexus Sorry it took me so long to merge this things have been a little hectic around here. But it looks good. Thanks!
